### ISSUE TITLE
VBR not working from inside container

### ISSUE THREAD

**Issue by tiwarishrijan** [vertica/vertica-containers#19]
We have installed vertica/vertica-ce latest version on kubernetes cluster. Inside POD we are trying to take backup using VBR script.

1. Initialization of backup location is success
   `vbr -t init -c backup_config.ini`

2. Back task fails with below error :
  `vbr -t backup -c backup_config.ini`

**Error: Unable to connect to backup host via password-less SSH: 127.0.0.1. ssh: connect to host 127.0.0.1 port 22: Connection refused**

**Backup FAILED.**

**Comment by NerdLogic** [comment]
Based on that error message, it looks like your config file is set to connect to localhost.  If you want to backup to the vertica-ce image, you would need to start the sshd service and set up password-less ssh access.

If you need help, you should contact technical support and give them the config file you are using.
