### ISSUE TITLE
COPY ... FROM VERTICA giving network error

### ISSUE THREAD

**Issue by shane-breeze** [vertica/vertica-containers#23]
Dear developers,

I've started a vertica container locally as a test database. I would like to load a subset of the data on my prod vertica database. I attempted:
```
CONNECT TO VERTICA <external_database> USER <user> PASSWORD <pass> ON <hostname>,<port>;

-- Create schema and tables

COPY <schema>.<table> FROM VERTICA <external_database>.<schema>.<table> DIRECT;
```

However, I get the following error:
```
SQL Error [4236] [V1001]: [Vertica][VJDBC](4236) ROLLBACK: One or more nodes did not open a data connection to this node.  This may indicate a network configuration problem.  Check that the private interfaces used for communication among the cluster hosts reside in the same subnet and are returned first by host address lookup
```

Running `select * from nodes;` on the database shows the node address 127.0.0.1 which I've read may cause an issue. But I'm not sure how to change it for the vertica container.

**Comment by NerdLogic** [comment]
Is this a question relating to a vertica container?  It sounds like a problem with the configuration of your production database.  I recommend contacting Vertica support or reading the Vertica documentation or forums.

I think this works to change ip addresses, although I'm not sure if this will solve your problem.
```
ALTER NODE node_name HOSTNAME 'NEW_NODE_IP';
```

**Comment by shane-breeze** [comment]
Is there a way I can test "COPY ... FROM VERTICA ..." on the vertica container without using my production database (i.e. to figure out if it's the container or the production database)?
